### PR TITLE
Memento Tutorial

### PR DESCRIPTION
**Pull request by AmritheshParavath**
Memento Tutorial added, can be found in a copy of the M2 demo scene. There is a gif in the drive that shows the tutorial. Basically, expands a section of the map where the player is explicitly told about mementos and gives them a chance to try it out.
https://drive.google.com/file/d/1yle1YkrQ5B6gMZGmQZLyOEg4reGfCOO6/view?usp=sharing

### CODE REVIEW

**Review by MGPAlpha — CHANGES_REQUESTED** [review]
Looks good for the most part. A few requests:
The changes to the Hostess Room 3 yarn script cause that script to break in the original m2 scene, as "hr3_hMarker1" doesn't exist in that scene. Please fix this so it doesn't break the base scene.

Second, what is the custom lantern material in Sprites/Forest/Materials for? As far as I can tell it's no different from the default material

**Comment by AmritheshParavath** [comment]
Got it, I'll fix those. Regarding the custom material, I wasn't sure how it got created but I'll delete it and make sure it doesn't break anything

**Comment by AmritheshParavath** [comment]
Alright, updated the scripts so that they should run on both scenes fine. I just wired them to Hostess (2) instead and since they are only called in scripts not found in the original M2 scene, it shouldn't conflict anymore.

**Comment by AmritheshParavath** [comment]
Also, the original navmesh for the M2 tutorial got messed up, but it should be easy to fix that by rebaking it. Didn't want to do it in this PR to avoid any merge conflicts

**Review by MGPAlpha — APPROVED** [review]
looks good

**Pull request merged**
