### PR TITLE
Updated .gitignore for a couple of files

### PR DESCRIPTION
**Pull request by alexjusung1**
I added .vsconfig (for Visual Studio) and .DS_Store (Mac attribute file) to the list

### CODE REVIEW

**Comment by MGPAlpha** [comment]
I can see why we should ignore .DS_Store, but why .vsconfig? My understanding is it's intended for setting up config for code across the repository. My local repo doesn't make a .vsconfig file, so what's in yours?

**Comment by alexjusung1** [comment]
I think my VS autogenerated the file when I first opened the project. It doesn't contain much right now:
`{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Workload.ManagedGame"
  ]
}
`

I assumed that it was unnecessary because the main branch didn't contain the file. Would it be better to run git commit on it instead?

**Review by MGPAlpha — APPROVED** [review]
Ok, I don't think we'll en up needing a .vsconfig for the distributed repo, so I'll go ahead and accept the PR and if we need it later it can just be added

**Comment by MGPAlpha** [comment]
Also, in future make sure not to work on main, because main should just be kept updated to the most recent version of my main. Instead work on feature branches. I'm not sure how familiar you are with git, dm me if you need more info on what that means

**Pull request merged**
